insert into public.matches
  (id, home_team, away_team, home_logo, away_logo, competition, date, time, timezone, venue, is_match_of_the_day)
values
  ('bl-2027-05-22-1-fc-union-berlin-borussia-monchengladbach', '1. FC Union Berlin', 'Borussia Mönchengladbach', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/1._FC_Union_Berlin_Logo.svg/330px-1._FC_Union_Berlin_Logo.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Borussia_M%C3%B6nchengladbach_logo.svg/330px-Borussia_M%C3%B6nchengladbach_logo.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'An der Alten Försterei', false),
  ('bl-2027-05-22-1-fsv-mainz-05-vfb-stuttgart', '1. FSV Mainz 05', 'VfB Stuttgart', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/1._FSV_Mainz_05_logo.svg/330px-1._FSV_Mainz_05_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/VfB_Stuttgart_1893_Logo.svg/330px-VfB_Stuttgart_1893_Logo.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'MEWA ARENA', false),
  ('bl-2027-05-22-fc-augsburg-hamburger-sv', 'FC Augsburg', 'Hamburger SV', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c5/FC_Augsburg_logo.svg/330px-FC_Augsburg_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Hamburger_SV_logo.svg/330px-Hamburger_SV_logo.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'WWK ARENA', false),
  ('bl-2027-05-22-sport-club-freiburg-borussia-dortmund', 'Sport-Club Freiburg', 'Borussia Dortmund', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6d/SC_Freiburg_logo.svg/330px-SC_Freiburg_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Borussia_Dortmund_logo.svg/330px-Borussia_Dortmund_logo.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'Europa-Park Stadion', false),
  ('bl-2027-05-22-rb-leipzig-tsg-hoffenheim', 'RB Leipzig', 'TSG Hoffenheim', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/04/RB_Leipzig_2014_logo.svg/330px-RB_Leipzig_2014_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Logo_TSG_Hoffenheim.svg/330px-Logo_TSG_Hoffenheim.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'Red Bull Arena', false),
  ('bl-2027-05-22-fc-bayern-munchen-eintracht-frankfurt', 'FC Bayern München', 'Eintracht Frankfurt', 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg/330px-FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/Eintracht_Frankfurt_crest.svg/330px-Eintracht_Frankfurt_crest.svg.png', 'Bundesliga', '2027-05-22', '17:30', 'Asia/Yerevan', 'Allianz Arena', false)
  on conflict (id) do nothing;
