insert into public.matches
  (id, home_team, away_team, home_logo, away_logo, competition, date, time, timezone, venue, is_match_of_the_day)
values
  ('l1-2027-05-29-olympique-lyonnais-paris-fc', 'Olympique Lyonnais', 'Paris FC', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Olympique_Lyonnais_logo.svg/330px-Olympique_Lyonnais_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9f/Paris_FC_logo.svg/330px-Paris_FC_logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Parc Olympique Lyonnais', false),
  ('l1-2027-05-29-olympique-de-marseille-fc-lorient', 'Olympique de Marseille', 'FC Lorient', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Olympique_de_Marseille_2026_logo.svg/330px-Olympique_de_Marseille_2026_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4c/FC_Lorient_logo.svg/330px-FC_Lorient_logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Stade Vélodrome', false),
  ('l1-2027-05-29-as-monaco-estac-troyes', 'AS Monaco', 'Estac Troyes', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/LogoASMonacoFC2021.svg/330px-LogoASMonacoFC2021.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/ESTAC_Troyes_Logo.svg/330px-ESTAC_Troyes_Logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Stade Louis II', false),
  ('l1-2027-05-29-paris-saint-germain-toulouse-fc', 'Paris Saint-Germain', 'Toulouse FC', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Paris_Saint-Germain_F.C..svg/330px-Paris_Saint-Germain_F.C..svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/63/Toulouse_FC_2018_logo.svg/330px-Toulouse_FC_2018_logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Parc des Princes', false),
  ('l1-2027-05-29-stade-rennais-fc-angers-sco', 'Stade Rennais FC', 'Angers SCO', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Stade_Rennais_FC.svg/330px-Stade_Rennais_FC.svg.png', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Angers_Sporting_Club_de_l%27Ouest_logo.svg/330px-Angers_Sporting_Club_de_l%27Ouest_logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Roazhon Park', false),
  ('l1-2027-05-29-rc-strasbourg-alsace-ogc-nice', 'RC Strasbourg Alsace', 'OGC Nice', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/80/Racing_Club_de_Strasbourg_logo.svg/330px-Racing_Club_de_Strasbourg_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2e/OGC_Nice_logo.svg/330px-OGC_Nice_logo.svg.png', 'Ligue 1', '2027-05-29', '02:00', 'Asia/Yerevan', 'Stade de la Meinau', false)
  on conflict (id) do nothing;
