insert into public.matches
  (id, home_team, away_team, home_logo, away_logo, competition, date, time, timezone, venue, is_match_of_the_day)
values
  ('pl-2027-05-15-liverpool-brentford', 'Liverpool', 'Brentford', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/250px-Liverpool_FC.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/330px-Brentford_FC_crest.svg.png', 'Premier League', '2027-05-15', '18:00', 'Asia/Yerevan', 'Anfield', false),
  ('pl-2027-05-15-manchester-united-leeds-united', 'Manchester United', 'Leeds United', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/330px-Manchester_United_FC_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/330px-Leeds_United_F.C._logo.svg.png', 'Premier League', '2027-05-15', '18:00', 'Asia/Yerevan', 'Old Trafford', false),
  ('pl-2027-05-15-sunderland-afc-afc-bournemouth', 'Sunderland AFC', 'AFC Bournemouth', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Logo_Sunderland.svg/330px-Logo_Sunderland.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/250px-AFC_Bournemouth_%282013%29.svg.png', 'Premier League', '2027-05-15', '18:00', 'Asia/Yerevan', 'Stadium of Light', false),
  ('pl-2027-05-23-afc-bournemouth-chelsea', 'AFC Bournemouth', 'Chelsea', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/250px-AFC_Bournemouth_%282013%29.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/330px-Chelsea_FC.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Vitality Stadium', false),
  ('pl-2027-05-23-brentford-hull-city', 'Brentford', 'Hull City', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/330px-Brentford_FC_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Hull_City_A.F.C._logo.svg/250px-Hull_City_A.F.C._logo.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Gtech Community Stadium', false),
  ('pl-2027-05-23-brighton-hove-albion-liverpool', 'Brighton & Hove Albion', 'Liverpool', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Brighton_and_Hove_Albion_FC_crest.svg/330px-Brighton_and_Hove_Albion_FC_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/250px-Liverpool_FC.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'American Express Stadium', false),
  ('pl-2027-05-23-everton-arsenal', 'Everton', 'Arsenal', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/330px-Everton_FC_logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/330px-Arsenal_FC.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Hill Dickinson Stadium', false),
  ('pl-2027-05-23-fulham-coventry-city', 'Fulham', 'Coventry City', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/330px-Fulham_FC_%28shield%29.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Coventry_City_FC_crest.svg/330px-Coventry_City_FC_crest.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Craven Cottage', false),
  ('pl-2027-05-23-leeds-united-sunderland-afc', 'Leeds United', 'Sunderland AFC', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/330px-Leeds_United_F.C._logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Logo_Sunderland.svg/330px-Logo_Sunderland.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Elland Road', false),
  ('pl-2027-05-23-manchester-city-aston-villa', 'Manchester City', 'Aston Villa', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/330px-Manchester_City_FC_badge.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/330px-Aston_Villa_FC_new_crest.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Etihad Stadium', false),
  ('pl-2027-05-23-newcastle-united-crystal-palace', 'Newcastle United', 'Crystal Palace', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/330px-Newcastle_United_Logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/330px-Crystal_Palace_FC_logo_%282022%29.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'St. James'' Park', false),
  ('pl-2027-05-23-nottingham-forest-ipswich-town', 'Nottingham Forest', 'Ipswich Town', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/120px-Nottingham_Forest_F.C._logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/330px-Ipswich_Town.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'The City Ground', false),
  ('pl-2027-05-23-tottenham-hotspur-manchester-united', 'Tottenham Hotspur', 'Manchester United', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/120px-Tottenham_Hotspur.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/330px-Manchester_United_FC_crest.svg.png', 'Premier League', '2027-05-23', '18:00', 'Asia/Yerevan', 'Tottenham Hotspur Stadium', false),
  ('pl-2027-05-30-arsenal-brighton-hove-albion', 'Arsenal', 'Brighton & Hove Albion', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/53/Arsenal_FC.svg/330px-Arsenal_FC.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Brighton_and_Hove_Albion_FC_crest.svg/330px-Brighton_and_Hove_Albion_FC_crest.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Emirates Stadium', false),
  ('pl-2027-05-30-aston-villa-tottenham-hotspur', 'Aston Villa', 'Tottenham Hotspur', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/Aston_Villa_FC_new_crest.svg/330px-Aston_Villa_FC_new_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Tottenham_Hotspur.svg/120px-Tottenham_Hotspur.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Villa Park', false),
  ('pl-2027-05-30-chelsea-brentford', 'Chelsea', 'Brentford', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/cc/Chelsea_FC.svg/330px-Chelsea_FC.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/2/2a/Brentford_FC_crest.svg/330px-Brentford_FC_crest.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Stamford Bridge', false),
  ('pl-2027-05-30-coventry-city-nottingham-forest', 'Coventry City', 'Nottingham Forest', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7b/Coventry_City_FC_crest.svg/330px-Coventry_City_FC_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/120px-Nottingham_Forest_F.C._logo.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Coventry Building Society Arena', false),
  ('pl-2027-05-30-crystal-palace-leeds-united', 'Crystal Palace', 'Leeds United', 'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/Crystal_Palace_FC_logo_%282022%29.svg/330px-Crystal_Palace_FC_logo_%282022%29.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/330px-Leeds_United_F.C._logo.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Selhurst Park', false),
  ('pl-2027-05-30-hull-city-newcastle-united', 'Hull City', 'Newcastle United', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Hull_City_A.F.C._logo.svg/250px-Hull_City_A.F.C._logo.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/330px-Newcastle_United_Logo.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'MKM Stadium', false),
  ('pl-2027-05-30-ipswich-town-everton', 'Ipswich Town', 'Everton', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Ipswich_Town.svg/330px-Ipswich_Town.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7c/Everton_FC_logo.svg/330px-Everton_FC_logo.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Portman Road', false),
  ('pl-2027-05-30-liverpool-afc-bournemouth', 'Liverpool', 'AFC Bournemouth', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0c/Liverpool_FC.svg/250px-Liverpool_FC.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/AFC_Bournemouth_%282013%29.svg/250px-AFC_Bournemouth_%282013%29.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Anfield', false),
  ('pl-2027-05-30-manchester-united-fulham', 'Manchester United', 'Fulham', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/330px-Manchester_United_FC_crest.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/330px-Fulham_FC_%28shield%29.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Old Trafford', false),
  ('pl-2027-05-30-sunderland-afc-manchester-city', 'Sunderland AFC', 'Manchester City', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/Logo_Sunderland.svg/330px-Logo_Sunderland.svg.png', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/330px-Manchester_City_FC_badge.svg.png', 'Premier League', '2027-05-30', '19:00', 'Asia/Yerevan', 'Stadium of Light', false)
  on conflict (id) do nothing;
